# Site settings
title: Data Analyst
email: siddhantrana1999@gmail.com
url: https://github.com/SiddhantRana5599/portfolio1
description: "Hello! I’m Siddhant, a naturally curious data enthusiast with a passion for personal knowledge management, data collection, and uncovering insights that spark new ideas. My journey into the data world began with a deep love for capturing, organizing, and distilling information, always looking for meaningful patterns. This passion led me to master SQL, Power BI, Excel, and Python—turning raw data into compelling stories and linking ideas in innovative ways.
"
keywords: "your keywords, separated by commas"
skills: "SQL - PowerBI - Python - Excel"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Siddhant Rana
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: www.linkedin.com/in/ranasiddhant5
  - title: github
    url: http://github.com/SiddhantRana5599

# Postal address (add as many lines as necessary)
address:
  - line: Delhi, India

# Credits content
credits: 'Github Pages'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
